//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMathsOperations")]
public interface IMathsOperations
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Add", ReplyAction="http://tempuri.org/IMathsOperations/AddResponse")]
    int Add(int arg1, int arg2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Add", ReplyAction="http://tempuri.org/IMathsOperations/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int arg1, int arg2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Multiply", ReplyAction="http://tempuri.org/IMathsOperations/MultiplyResponse")]
    int Multiply(int arg1, int arg2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Multiply", ReplyAction="http://tempuri.org/IMathsOperations/MultiplyResponse")]
    System.Threading.Tasks.Task<int> MultiplyAsync(int arg1, int arg2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Subtract", ReplyAction="http://tempuri.org/IMathsOperations/SubtractResponse")]
    int Subtract(int arg1, int arg2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperations/Subtract", ReplyAction="http://tempuri.org/IMathsOperations/SubtractResponse")]
    System.Threading.Tasks.Task<int> SubtractAsync(int arg1, int arg2);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMathsOperationsChannel : IMathsOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MathsOperationsClient : System.ServiceModel.ClientBase<IMathsOperations>, IMathsOperations
{
    
    public MathsOperationsClient()
    {
    }
    
    public MathsOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MathsOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathsOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathsOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int arg1, int arg2)
    {
        return base.Channel.Add(arg1, arg2);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int arg1, int arg2)
    {
        return base.Channel.AddAsync(arg1, arg2);
    }
    
    public int Multiply(int arg1, int arg2)
    {
        return base.Channel.Multiply(arg1, arg2);
    }
    
    public System.Threading.Tasks.Task<int> MultiplyAsync(int arg1, int arg2)
    {
        return base.Channel.MultiplyAsync(arg1, arg2);
    }
    
    public int Subtract(int arg1, int arg2)
    {
        return base.Channel.Subtract(arg1, arg2);
    }
    
    public System.Threading.Tasks.Task<int> SubtractAsync(int arg1, int arg2)
    {
        return base.Channel.SubtractAsync(arg1, arg2);
    }
}
